### ISSUE TITLE
GetInternalTransactionByHash should provide a value in BNB

### ISSUE THREAD

**Issue by migregorio** [dannyhu/AtomicCore#4]
GetInternalTransactionByHash should provide the TxValue in BNB, I think. But it currently converts it to an unrecognized value (maybe ETH). Either way, I think it should just provide the value returned by BscScan and not be converted at all.

**Comment by dannyhu** [comment]
I will check the code and fix related bugs




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dannyhu/AtomicCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月16日(星期三) 凌晨4:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dannyhu/AtomicCore] GetInternalTransactionByHash should provide a value in BNB (Issue #4)





 
GetInternalTransactionByHash should provide the TxValue in BNB, I think. But it currently converts it to an unrecognized value (maybe ETH). Eitherway, I think it should just provide the value returned by BscScan and not be converted at all.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dannyhu** [comment]
please use version V1.0.4




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dannyhu/AtomicCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月16日(星期三) 凌晨4:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dannyhu/AtomicCore] GetInternalTransactionByHash should provide a value in BNB (Issue #4)





 
GetInternalTransactionByHash should provide the TxValue in BNB, I think. But it currently converts it to an unrecognized value (maybe ETH). Eitherway, I think it should just provide the value returned by BscScan and not be converted at all.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by migregorio** [comment]
This is resolved. Thank you!
