### ISSUE TITLE
GetBNBLastPrice() JsonSerializationException

### ISSUE THREAD

**Issue by migregorio** [dannyhu/AtomicCore#6]
**I encounter an exception when I run the following:**
var BnbPrice = _bscClient.GetBNBLastPrice().Result.Ethusd;

**The following is the exception message:**
Newtonsoft.Json.JsonSerializationException: 'Error converting value "22500514445379500000000000" to type 'AtomicCore.BlockChain.BscscanAPI.BscLastPriceJson'. Path 'result', line 1, position 66.'

Inner Exception
ArgumentException: Could not cast or convert from System.String to AtomicCore.BlockChain.BscscanAPI.BscLastPriceJson.

**Additional details:**
The value shown in the error changes every time I execute the code.

**Comment by migregorio** [comment]
I think I see the bug. The parameter being used is "bnbsupply" but it should be "bnbprice", I think.

```
        private BscscanSingleResult<BscLastPriceJson> GetBNBLastPrice(BscNetwork network = BscNetwork.BscMainnet)
        {
            string url = this.GetRestUrl(network, BscModule.Stats, "**bnbsupply**");

            string resp = this.RestGet(url);
            BscRpcJson<BscLastPriceJson> jsonResult = ObjectParse<BscRpcJson<BscLastPriceJson>>(resp);

            return new BscscanSingleResult<BscLastPriceJson>()
            {
                Status = BscscanJsonStatus.Success,
                Message = string.Empty,
                Result = jsonResult.Result
            };
        }
```

**Comment by migregorio** [comment]
I could do a pull request if you'd like. Just let me know. Thank you!

**Comment by dannyhu** [comment]
Yes, it's wrong, I'll fix it right away




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dannyhu/AtomicCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 凌晨5:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [dannyhu/AtomicCore] GetBNBLastPrice() JsonSerializationException (Issue #6)





 
I think I see the bug. The parameter being used is "bnbsupply" but it should be "bnbprice", I think.
         private BscscanSingleResult<BscLastPriceJson&gt; GetBNBLastPrice(BscNetwork network = BscNetwork.BscMainnet)         {             string url = this.GetRestUrl(network, BscModule.Stats, "**bnbsupply**");             string resp = this.RestGet(url);             BscRpcJson<BscLastPriceJson&gt; jsonResult = ObjectParse<BscRpcJson<BscLastPriceJson&gt;&gt;(resp);             return new BscscanSingleResult<BscLastPriceJson&gt;()             {                 Status = BscscanJsonStatus.Success,                 Message = string.Empty,                 Result = jsonResult.Result             };         }  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dannyhu** [comment]
Please use V1.0.5




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dannyhu/AtomicCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 凌晨2:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [dannyhu/AtomicCore] GetBNBLastPrice() JsonSerializationException (Issue #6)





 
I could do a pull request if you'd like. Just let me know. Thank you!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by migregorio** [comment]
Thank you! I'll test this in an hour or so. I'm sure it works great now.
